# Generated by Django 5.0.6 on 2024-06-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postId', models.BigAutoField(db_column='BID', primary_key=True, serialize=False)),
                ('topic', models.CharField(default=None, max_length=40)),
                ('postText', models.TextField(default=None, max_length=1600)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
