# Generated by Django 5.0.6 on 2024-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigAutoField(db_column='BID', primary_key=True, serialize=False),
        ),
    ]
